spring.application.name=hospital-management
server.port=4000

spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.root=INFO

# Billing Service gRPC
billing.service.address=localhost
billing.service.grpc.port=9001
